name: SMIB_Transact Workflow

on:
  push:
    branches: [ "*" ]
      
  pull_request:
    branches: [ "*" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
   

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
        
    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
        
    - name: Set up Helix Hub credentials in settings.xml
      run: |
        mkdir -p ~/.m2
        cat > ~/.m2/settings.xml <<EOF
        <servers>
          <server>
            <id>smib-sysenact</id>
            <username>YashithSasmitha</username>
            <password>@Yashith0306</password>
          </server>
          
        </servers>
        EOF
    

    - name: Build with Maven
      run: MAVEN_OPTS="-Xmx1024m" mvn -T 1C -B package -U --file pom.xml --settings .maven/settings.xml -DskipTests
      
    - name: Generate timestamp
      id: timestamp
      run: echo "timestamp=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV
        
    - name: Upload JAR Artifact
      uses: actions/upload-artifact@v4
      with:
        name: smibtransact-jar-${{ env.timestamp }}
        path: target/*.jar

    - name: Publish to Helix TeamHub
      run: mvn deploy -DskipTests --settings .maven/settings.xml
      env:
        HELIX_USERNAME: YashithSasmitha
        HELIX_PASSWORD: @Yashith0306